vim.loader.enable()

require("options")
require("keymaps")

require("plugins.which-key")
require("plugins.toggleterm")
require("plugins.gitsigns")
require("plugins.aerial")
require("plugins.snacks")
require("plugins.snipe")
require("plugins.devicons")
require("plugins.bufferline")
require("plugins.autopairs")
require("plugins.luasnip")
require("plugins.blink")
